datasource:
  url: ${SPRING_DATASOURCE_URL}
  username: ${SPRING_DATASOURCE_USERNAME}
  password: ${SPRING_DATASOURCE_PASSWORD}
  driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret: ${jwt.secret}
  access-token-validity-in-milliseconds: ${jwt.access-token-validity-in-milliseconds}
  refresh-token-validity-in-milliseconds: ${jwt.refresh-token-validity-in-milliseconds}